export const excludedMesh = {
  rt_midsole_tape_a: true,
  rt_midsole_tape_b: true,
  rt_midsole_tape_c: true,
  rt_toe_bumper_a: true,
  rt_toe_bumper_b: true,
  rt_toe_bumper_c: true,
  rt_toe_bumper_d: true,
  lf_midsole_tape_a: true,
  lf_midsole_tape_b: true,
  lf_midsole_tape_c: true,
  lf_toe_bumper_a: true,
  lf_toe_bumper_b: true,
  lf_toe_bumper_c: true,
  lf_toe_bumper_d: true,
  rt_tooling_grp: true,
  lf_tooling_grp: true,
  lf_midsole_topline: true,
  rt_midsole_topline: true,
  rt_midsole_pinstripe: true,
  lf_midsole_pinstripe: true,
  rt_shoe_grp: true,
  lf_shoe_grp: true,
};
